name: Build

on: [ push ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1.31.4
        with:
          perl-version: latest
      - name: Configure
        run: |
          cd openssl
          perl Configure
      - name: Build
        run: make
